baseURL = 'https://jeakob.github.io/blog/'
languageCode = 'en-us'
title = 'Problem Solver Blog'
theme = "unix"
pagination.pagerSize = 5
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe= true


[params]
    github_url = "https://github.com/jeakob"


[taxonomies]
    series = 'series'
    tags = 'tags'